package es.gealty.bean;
// Generated 30-abr-2017 13:21:47 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * Location generated by hbm2java
 */
public class Location implements java.io.Serializable {

	private Integer id;
	private Seed seed;
	private String longitude;
	private String latitude;
	private Date dateInsert;

	public Location() {
	}

	public Location(Date dateInsert) {
		this.dateInsert = dateInsert;
	}

	public Location(Seed seed, String longitude, String latitude, Date dateInsert) {
		this.seed = seed;
		this.longitude = longitude;
		this.latitude = latitude;
		this.dateInsert = dateInsert;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Seed getSeed() {
		return this.seed;
	}

	public void setSeed(Seed seed) {
		this.seed = seed;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public Date getDateInsert() {
		return this.dateInsert;
	}

	public void setDateInsert(Date dateInsert) {
		this.dateInsert = dateInsert;
	}

}
