package es.gealty.bean;
// Generated 30-abr-2017 13:21:47 by Hibernate Tools 5.2.1.Final

/**
 * Metadata generated by hbm2java
 */
public class Metadata implements java.io.Serializable {

	private Integer id;
	private Seed seed;
	private String field;
	private String value;

	public Metadata() {
	}

	public Metadata(Seed seed, String field, String value) {
		this.seed = seed;
		this.field = field;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Seed getSeed() {
		return this.seed;
	}

	public void setSeed(Seed seed) {
		this.seed = seed;
	}

	public String getField() {
		return this.field;
	}

	public void setField(String field) {
		this.field = field;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
