package es.gealty.bean;
// Generated 30-abr-2017 13:21:47 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Seed generated by hbm2java
 */
public class Seed implements java.io.Serializable {

	private Integer id;
	private Set seedNames = new HashSet(0);
	private Set metadatas = new HashSet(0);
	private Set locations = new HashSet(0);

	public Seed() {
	}

	public Seed(Set seedNames, Set metadatas, Set locations) {
		this.seedNames = seedNames;
		this.metadatas = metadatas;
		this.locations = locations;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Set getSeedNames() {
		return this.seedNames;
	}

	public void setSeedNames(Set seedNames) {
		this.seedNames = seedNames;
	}

	public Set getMetadatas() {
		return this.metadatas;
	}

	public void setMetadatas(Set metadatas) {
		this.metadatas = metadatas;
	}

	public Set getLocations() {
		return this.locations;
	}

	public void setLocations(Set locations) {
		this.locations = locations;
	}

}
