package es.gealty.bean;
// Generated 30-abr-2017 13:21:47 by Hibernate Tools 5.2.1.Final

/**
 * SeedName generated by hbm2java
 */
public class SeedName implements java.io.Serializable {

	private Integer id;
	private Seed seed;
	private String name;

	public SeedName() {
	}

	public SeedName(Seed seed, String name) {
		this.seed = seed;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Seed getSeed() {
		return this.seed;
	}

	public void setSeed(Seed seed) {
		this.seed = seed;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
